# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Publish NuGet Package

on:
    push:
        tags: ['v*.*.*']
    workflow_dispatch:

jobs:
    ci:
        uses: ./.github/workflows/ci.yml

    publish:
        needs: ci
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        strategy:
            matrix:
                project: [
                    'src/AndreyAkaSkif.ServiceDefaults/AndreyAkaSkif.ServiceDefaults.csproj',
                    'src/AndreyAkaSkif.ServiceDefaults.OpenApi/AndreyAkaSkif.ServiceDefaults.OpenApi.csproj',
                    'src/AndreyAkaSkif.ServiceDefaults.Swagger/AndreyAkaSkif.ServiceDefaults.Swagger.csproj',
                    'src/AndreyAkaSkif.ServiceDefaults.Serilog/AndreyAkaSkif.ServiceDefaults.Serilog.csproj',
                    'src/AndreyAkaSkif.ServiceDefaults.PostgreSQL/AndreyAkaSkif.ServiceDefaults.PostgreSQL.csproj',
                ]
        steps:
            - name: 🛒 Checkout
              uses: actions/checkout@v7

            - name: ✨ Setup .NET
              uses: actions/setup-dotnet@v6
              with:
                dotnet-version: '10.0.x'

            - name: 💾 Cache NuGet packages
              uses: actions/cache@v6
              with:
                path: ~/.nuget/packages
                key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
                restore-keys: ${{ runner.os }}-nuget-

            - name: 🚚 Restore
              run: dotnet restore

            - name: 🛠️ Build
              run: dotnet build --configuration Release --no-restore

            - name: 📦 Pack ${{ matrix.project }}
              run: dotnet pack ${{ matrix.project }} --configuration Release --output ./nupkgs

            - name: 🚀 Publish ${{ matrix.project }} to GitHub Packages
              run: |
                  dotnet nuget push ./nupkgs/*.nupkg \
                    --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
                    --api-key ${{ secrets.GH_PACKAGES_TOKEN }} \
                    --skip-duplicate
